#!/bin/bash

echo "##########################"
echo "Starting Mini Race Control"
echo "##########################"

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


count=0
echo "will now wait for google"
until $(curl --output /dev/null --silent --head --fail https://www.google.ch); do
    (( count++ ));
    if [ ${count} -ge 30 ]; then
        echo ' [timed out]';
        sudo lsof -i
        echo "https://www.google.ch"
        curl https://www.google.ch;
        exit 1;
    fi;
    printf '.';
    sleep 1;
done
echo " [server responded after approx ${count}s]"

set -e

cd $DIR
sudo -u pi git pull

echo "##########################"
echo "sync"

sync

echo "##########################"
echo "start pirace"

sudo python PiRace.py


echo "##########################"
echo "done"
echo "##########################"
